# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "SenaYamato Blog"
description: > # this means to ignore newlines until "email:"
   技術メモだったりしょうもないことだったり

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/icon.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'SenaYamato'
author: 'SenaYamato'
author_image: "/assets/images/icon.png"

paginate:	5

url: "https://nested-loops.github.io"
baseurl: "/senayamato"
#used to display twitter cards
twitter_handle: '@nestedloop_'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/nestedloop_
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/nested-loops
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
